version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - ./dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.4.1-apache
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 10080:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

